### ISSUE TITLE
Neue Regel für Lokale Titelaufnahmen Erwerbung

### ISSUE THREAD

**Issue by florianruckelshausen** [florianruckelshausen/cbs2folio-transformations#10]
PPN 489381537

Im CBS gibt es ca. 300 Lokale Titelaufnahmen für Erwerbungszwecke. Die Materialart 002@ der Sätze ist lac, lau oder lay. Aktuell landen sie im "Standort unbekannt", weil sie das Signaturfeld für längere Kommentare zweckentfremden. Ich habe einen gesonderten Standort "Lokale Titelaufnahmen Erwerbung" angelegt.

Wir bräuchten aus meiner Sicht eine Regel, die sich vor die Abteilungs-/Signaturenregeln setzt und nach den ersten beiden Position in 002@ schaut. Sind diese "La" dann wird der Standort "Lokale Titelaufnahmen Erwerbungs" zugeordnet.

**Comment by michaelfreiberg** [comment]
Eingefügt mit dem Commit eff2d21 und auch schon mit Laa, Lac, Lau und Lay getestet.
