### ISSUE TITLE
Fernleihstandorte einbinden

### ISSUE THREAD

**Issue by florianruckelshausen** [florianruckelshausen/cbs2folio-transformations#4]
@michaelfreiberg Ich habe eben zwei neue Standorte für die Fernleihen ergänzt, die wir inzwischen in FOLIO angelegt haben: einmal Ferlnleihen und einmal Fernleihen/Lesesaal. Hierfür bräuchten wir noch Regeln in der holding-items-hebis-iln204.xsl, denn die Kurztitelaufnahmen für Fernleihen werden im CBS angelegt und nicht mehr als lokale Titelaufnahmen. Sie laufen also über den CBS-Konnektor und müssen dann einen Standort bekommen.

Folgende Kriterien sind aus meiner Sicht denkbar

- Signatur fängt mit "FL" an
- Materialart (Kategorie 0500) ist Luf
- Buchnummer (Kategorie 8200) fängt mit "A" an

Zudem wäre ein Unterscheidung der beiden Standorte nach Ausleihindikator nötig
- Ausleihindikator "u" oder "d" zum Standort UBFernleihen
- Ausleihindikator "i" zum Standort UBFernleihenLesesaal

Ich hoffe das geht so. Wenn nicht sag nochmal Bescheid.

**Comment by michaelfreiberg** [comment]
Ich habe den Fall der Fernleihen in dem Commit 9a8e494 eingebaut und auch mit XML-Testdaten erfolgreich ausprobiert. Für den Fall, dass der Ausleihindikator nicht "u", "d" oder "i" ist, habe ich _ILN204/CG/UB/Unbekannt_ als Default eingefügt. Die XSLT ist auch schon im Harvester eingepflegt. Schau doch mal, ob es auch in FOLIO ankommt.

**Comment by florianruckelshausen** [comment]
Ja klappt. Ich hatte die codes2uuid-hebis-iln204.xsl noch nicht auf dem Harvester aktualisiert, daher ging es erst schief. Jetzt klappt es aber. Hier die Beispiel-PPN aus dem CBS-Testsyste: 488542359.
