### ISSUE TITLE
Umzug ZNL-Magazin nach Pohlheim

### ISSUE THREAD

**Issue by florianruckelshausen** [florianruckelshausen/cbs2folio-transformations#7]
Hier noch die Liste der Signaturgruppen, die Susanne am Freitag als handschriftlichen Zettel dabei hatte. Sie sind von der ZNL nach Pohlheim gezogen. Die Bände sind schon auf den Abteilungscode !000!

a) Signaturanfang "MAG 002 ..." sollte derzeit auf das ZNL-Magazin zeigen. Hier müsste jetzt nach Fächergruppen getrennt werden:

- agr, ern, mat, nat, phy, tec, umw müssen nach Pohlheim zeigen
- alle anderen mit MAG 002 bleiben zunächst im ZNL-Magazin.

b) Signaturanfragen "140 mag" (Monos + ZS) sollte derzeit auch auf das ZNL-Magazin zeigen. Hier reicht wahrscheinlich, das Umlenken des Mappings auf Pohlheim.

Wegen der anderen Signaturgruppen muss ich Susanne nochmal fragen.

**Comment by michaelfreiberg** [comment]
Ist umgesetzt in b330905c43d45878825c030752a78ca4c60c4d1d
