### ISSUE TITLE
Regel für übergeordnete Bibliografie Dummy-Aufnahmen (70xy do)

### ISSUE THREAD

**Issue by florianruckelshausen** [florianruckelshausen/cbs2folio-transformations#9]
Es gibt ca. 1.300 Aufnahmen mit Selektionscode do (CBS-Suche f knz do). Die Titel sind nicht in unserem Bestand und wurden aus bibliografischen Gründen angelegt. Typischerweise sind dann Artikel/Kapitel von JLU-Autor*inn*en damit verknüpft. Erkennbar sind die Titel ab 70xy(208@) = do.

Aktuell landen die Titel im Standort Unbekannt der UB. Aus meiner Sicht müssten sie in den Bereich "Aufsatzkatalogisate und übergeordnete Aufnahmen". Da dieser langsam unübersichtlich wird, habe ich mal einen Standort "do-Aufnahmen" in FOLIo erstelllt. Wir bräuchten also eine Regel, die auf das "do" triggert und diesen neuen Standort fest zuweist.

Weiteres ToDo wäre die HDS-Anzeige solcher Aufnahmen, dafür mache ich dann aber im FOLIO-HDS-Konnektor ein Ticket auf.

**Comment by michaelfreiberg** [comment]
Mit dem Commit 0443d4f habe ich einen Versuch unternommen, kann ihn aber leider nicht testen. Änderungen triggern den Harvester nicht. Vermutlich weil kein Gießener Bestand anhängt?

**Comment by florianruckelshausen** [comment]
Es hängt ja eine Exemplardatensatz von uns an den Beständen, d.h. von der datentechnischen Sicht sieht es erstmal so aus als hätten wir Bestand. Die VZ scheint gestern den Harvester abgestellt zu haben. In der Harvester Verwaltungs App sieht man unter "Jobs", dass der letzte Job gestern um 17:42 Uhr lief, wobei ich meine, dass die Zeitangaben in der App nicht der wirklichen lokalen Zeit entsprechen. Ich vermute die VZ hat das im Hinblick auf das für heute geplante Backup unseres Testsystems gemacht. Wahrscheinlich müssen wir es dann einfach nächste Woche nochmal ausprobieren.

**Comment by michaelfreiberg** [comment]
In meiner XSLT waren ein Syntax- und ein Logikfehler, die ich mit 8361c60f4b342c8eb6cc0bcbdc5dd49ccf22a331 und 4a99865791293ba70ede731248ef8e0c29cc4bee behoben habe.

Dummy-Do-Standort nun erfolgreich getestet mit PPN 481559299.
